# Generated by Django 4.0.1 on 2022-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bece',
            name='quota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bece',
            name='quota2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bece',
            name='ClosingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bece',
            name='StartingDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bece',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
