# Generated by Django 4.0.1 on 2022-09-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_bece_quota_bece_quota2_alter_bece_closingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bece',
            name='SchoolType',
            field=models.CharField(blank=True, choices=[('0', 'PRIVATE'), ('1', 'PUBLIC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bece',
            name='StartingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
