# Generated by Django 3.2.3 on 2022-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_requestid_bece_schoolids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bece',
            name='NumberOfCandidates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
