# Generated by Django 3.2.3 on 2022-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_bece_numberofcandidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bece',
            name='TownCity',
        ),
        migrations.AddField(
            model_name='bece',
            name='adminemail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
