# Generated by Django 4.1.1 on 2022-09-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinNo', models.TextField()),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.CharField(max_length=255, null=True)),
                ('transactionRef', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('bulknumber', models.BigIntegerField(null=True)),
                ('ExamType', models.CharField(blank=True, choices=[('1', 'M.C'), ('2', 'P.S')], default=0, max_length=100, null=True)),
            ],
        ),
    ]
